In [6]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer

In [7]:
df = pd.read_csv("Reviews.csv", nrows=50000)

print(df.shape)

(50000, 10)


In [8]:
light_reviews = df[df["Text"].str.contains("light", case=False, na=False)]

print("Total reviews containing 'light':", len(light_reviews))

Total reviews containing 'light': 3511


In [9]:
for idx, review in light_reviews['Text'].head(50).items():
    print("\n")
    print(review)
    print("="*100)



This is a confection that has been around a few centuries.  It is a light, pillowy citrus gelatin with nuts - in this case Filberts. And it is cut into tiny squares and then liberally coated with powdered sugar.  And it is a tiny mouthful of heaven.  Not too chewy, and very flavorful.  I highly recommend this yummy treat.  If you are familiar with the story of C.S. Lewis' "The Lion, The Witch, and The Wardrobe" - this is the treat that seduces Edmund into selling out his Brother and Sisters to the Witch.


I got a wild hair for taffy and ordered this five pound bag. The taffy was all very enjoyable with many flavors: watermelon, root beer, melon, peppermint, grape, etc. My only complaint is there was a bit too much red/black licorice-flavored pieces (just not my particular favorites). Between me, my kids, and my husband, this lasted only two weeks! I would recommend this brand of taffy -- it was a delightful treat.


I roast at home with a stove-top popcorn popper (but I do it outsid

In [10]:
sentences = [
    "This is a confection that has been around a few centuries. It is a light, pillowy citrus gelatin with nuts.",
    
    "The packaging was broken and let too much light inside the box.",
    
    "It is not light and fluffy. It is very gooey."
]

In [11]:
vectorizer = CountVectorizer()

X = vectorizer.fit_transform(sentences)

dense_matrix = X.toarray()

print(dense_matrix)

[[0 1 1 0 0 1 1 1 1 0 1 0 1 0 2 1 0 1 0 0 1 0 1 1 0 1 0 0 0 1]
 [1 0 0 1 1 0 0 0 0 0 0 0 0 1 0 0 1 1 1 0 0 1 0 0 2 0 1 0 1 0]
 [1 0 0 0 0 0 0 0 0 1 0 1 0 0 2 2 0 1 0 1 0 0 0 0 0 0 0 1 0 0]]


In [12]:
vec_1 = dense_matrix[0]
vec_2 = dense_matrix[1]
vec_3 = dense_matrix[2]

print(vec_1)
print(vec_2)
print(vec_3)

[0 1 1 0 0 1 1 1 1 0 1 0 1 0 2 1 0 1 0 0 1 0 1 1 0 1 0 0 0 1]
[1 0 0 1 1 0 0 0 0 0 0 0 0 1 0 0 1 1 1 0 0 1 0 0 2 0 1 0 1 0]
[1 0 0 0 0 0 0 0 0 1 0 1 0 0 2 2 0 1 0 1 0 0 0 0 0 0 0 1 0 0]


In [13]:
sim_12 = np.dot(vec_1, vec_2)

sim_13 = np.dot(vec_1, vec_3)

print("Similarity (Sentence 1 vs Sentence 2):", sim_12)

print("Similarity (Sentence 1 vs Sentence 3):", sim_13)

Similarity (Sentence 1 vs Sentence 2): 1
Similarity (Sentence 1 vs Sentence 3): 7
